### ISSUE TITLE
Installing inside venv

### ISSUE THREAD

**Issue by acosonic** [jonathantissot/full_dns_records_details#1]
Hi I've stumbled upon:

`Building wheels for collected packages: PyYAML
  Building wheel for PyYAML (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/acop/pentest/full_dns_records_details/env/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ekr334d7/PyYAML/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ekr334d7/PyYAML/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-n5p9tn5r
       cwd: /tmp/pip-install-ekr334d7/PyYAML/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for PyYAML
  Running setup.py clean for PyYAML
Failed to build PyYAML
`

Then I have installed wheel later, looks like it was a missing requirement...

**Comment by jonathantissot** [comment]
Thank you @acosonic 
I just added the requirement. This is not supposed to fail, but I did not do a full test on several OS.
Thank you for spotting it and raising it here.

https://github.com/jonathantissot/full_dns_records_details/commit/daf2d8e782f6cd9d109e80aa314ed163c661e4ee

Cheers!
